export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
export const DELETE_SINGLE_USER = "DELETE_SINGLE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

